export default {
    'navbar.lang': 'English',
    'Home':'Home',
    'dashboard':'dashboard',
    'CRM':'CRM',
    'Companies':'Companies',
    'Contacts':'Contacts',
    'Events':'Events',
    'Draft':'Draft',
    'Upcoming':'Upcoming',
    'Current':'Current',
    'Past':'Past',
    'Finance':'Finace',
    'Information':'Infomation',
    'Payment':'Payment',
    'userInterface':'userInterface',
    'event.menu.SET UP':'SET UP',
    'event.menu.General Settings':'General Settings',
    'event.menu.Registration Form':'Registration Form',
    'event.menu.Tickets & Coupons':'Tickets & Coupons',
    'event.menu.Content Settings':'Content Settings',
    'event.menu.Content Layout':'Content Layout',
    'event.menu.Promote':'Promote',
    'event.menu.Invitation':'Invitation',
    'event.menu.Manage':'Manage',
    'event.menu.Registration List':'Registration List',
    'event.menu.Finance':'Finance',
    'event.menu.Paymetns':'Paymetns',
    
    'event.content.Speakers':'Speakers',
    'event.content.Agenda':'Agenda',
    'event.content.Add venues':'Add venues',
    'event.content.Sponsors & Partners':'Sponsors & Partners',
    'event.content.Documents':'Documents',
    'event.content.Saved':'Saved',
    'event.content.Add speakers':'Add speakers',
    'event.content.Edit speakers':'Edit speakers',
    'event.content.Delete speakers':'Delete speakers',
    'event.content.Preview speakers':'Preview speakers',
    'event.content.Search for the speaker':'Search for the speaker',
    'event.content.Add a new speaker':'Add a new speaker',
    'event.content.Speakers List':'Speakers List',
    'event.content.Upload avatar':'Upload avatar',
    'event.content.First name':'First name',
    'event.content.Last name':'Last name',
    'event.content.Position':'Position',
    'event.content.Company':'Company',
    'event.content.E-mail':'E-mail',
    'event.content.Order by':'Order by',
    'event.content.Website':'Website',
    "event.content.Description of your event's speaker":"Description of your event's speaker",
    'event.content.Cancel':'Cancel',
    'event.content.Day 1':'Day 1',
    'event.content.Track':'Track',
    'event.content.New Track':'New Track',
    'event.content.Edit Track':'Edit Track',
    'event.content.Delete Track':'Delete Track',
    'event.content.Session ':'Session',
    'event.content.Create a new session':'Create a new session',
    'event.content.Edit a new session':'Edit a new session',
    'event.content.Delete a new session':'Delete a new session',
    'event.content.Break':'Break',
    'event.content.Create a new break':'Create a new break',
    'event.content.Edit a new break':'Edit a new break',
    'event.content.Delete a new break':'Delete a new break',
    'event.content.Gap':'Gap',
    'event.content.Add a time gap':'Add a time gap',
    'event.content.Edit a time gap':'Edit a time gap',
    'event.content.Delete a time gap':'Delete a time gap',
    'event.content.Name':'Name',
    'event.content.Detailed address':'Detailed address',
    'event.content.Title':'Title',
    'event.content.Start time':'Start time',
    'event.content.End time':'End time',
    'event.content.Details':'Details',
    'event.content.Address':'Address',
    'event.content.Time':'Time',
    'event.content.GAP Time':'GAP Time',
    'event.content.Replenish meeting time by taking breaks':'Replenish meeting time by taking breaks',
    'event.content.Add a venue manually':'Add a venue manually',
    'event.content.Sort alphabetically':'Sort alphabetically',
    'event.content.Sort on usage':'Sort on usage',
    'event.content.Please input keywords':'Please input keywords',
    'event.content.Used/Saved venues':'Used/Saved venues',
    'event.content.Venue name':'Venue name',
    'event.content.Edit address':'Edit address',
    'event.content.Click here to upload a file':'Click here to upload a file',
    'event.content.Upload':'Upload',
    'event.content.Reset':'Reset',
    'event.content.Organizations':'Organizations',
    'event.content.Edit':'Edit',
    'event.content.Organization category':'Organization category',
    'event.content.Please input keywords':'Please input keywords',
    'event.content.Add Sponsors to organization':'Add Sponsors to organization',
    'event.content.Add sponsors':'Add sponsors',
    'event.content.Back to add sponsors':'Back to add sponsors',
    'event.content.Edit sponsors':'Edit sponsors',
    'event.content.Delete sponsors':'Delete sponsors',
    'event.content.Add sponsors':'Add sponsors',
    'event.content.Sponsors description':'Sponsors description',
    'event.content.Type of sponsorship amount':'Type of sponsorship amount',
    'event.content.Sponsorship amount':'Sponsorship amount',
    'event.content.Note':'Note',
    'event.content.Hide the sponsor on the event page':'Hide the sponsor on the event page',
    'event.content.Close':'Close',
    'event.content.Document list':'Document list',
    'event.content.Upload documents':'Upload documents',
    'event.content.Delete documents':'Delete documents',
    'event.content.No attached documents':'No attached documents',
    'event.content.Add documents':'Add documents',
    'event.content.Upload attached documents, which can be viewed or downloaded by participants':'Upload attached documents, which can be viewed or downloaded by participants',
}