export default {
    //tila
    'navbar.lang': 'English',
    'navbar.Welcome': 'Welcome！',
    'navbar.Please Login': 'Please Login！',
    'Home':'Home',
    'dashboard':'Dashboard',
    'CRM':'CRM',
    'Companies':'Companies',
    'Contacts':'Contacts',
    'Events':'Events',
    'Draft':'Draft',
    'Upcoming':'Upcoming',
    'InProgress':'In Progress',
    'Past':'Past',
    'Finance':'Finance',
    'Invoice':'Collection',
    'Payment':'Payment',
    'userInterface':'userInterface',
    'Ticket':'Ticket',
    'Promotion':'Promotion',
    'Exit':'Exit Event Management',
    'event.menu.SET UP':'SET UP',
    'event.menu.General Settings':'General Settings',
    'event.menu.Registration Form':'Registration List',
    'event.menu.Tickets & Coupons':'Ticket Settings',
    'event.menu.Content Settings':'Content Settings',
    'event.menu.Content Layout':'Content Layout',
    'event.menu.Promote':'Promote',
    'event.menu.Invoice':'Invoice',
    'event.menu.Invitation':'Invitation',
    'event.menu.EmailMarketing':'Email Marketing',
    'event.menu.Manage':'Manage',
    'event.menu.Registration List':'Attendee List',
    'event.menu.Finance':'Finance',
    'event.menu.summary':'Summary',
    'event.menu.speakers':'Speakers',
    'event.menu.agenda':'Agenda',
    'event.menu.venue':'Venue',
    'event.menu.sponsors':'Sponsors & Partners',
    'event.menu.documents':'Documents',
    'event.menu.Paymetns':'Payment',
    'event.table.eventId':'Event id',
    'event.table.eventTitle':'Event title',
    'event.table.location':'Location',
    'event.table.startDate':'Start Date',
    'event.table.creation':'Creation Time',
    'event.table.attendance':'Attendance',
    'event.table.checkedIn':'Checked In',
    'event.table.manage':'Manage',
    'event.table.edit':'Edit',
    'event.table.preview':'Preview',
    'event.table.duplicate':'Duplicate',
    'event.table.delete':'Delete',
    'event.table.action':'Action',
    'event.createEvent':'Create Event',
    'event.create':'Please fill in all the event details',
    'event.createEventDes':'Create a new event',
    'event.common.eventTitle':'Event Title',
    'event.common.Language':'Language',
    'event.common.startDate':'Start date',
    'event.common.preview':'Preview',
    'event.common.endDate':'End date',
    'event.common.publish':'Publish',
    'event.common.startTime':'Start time',
    'event.common.endTime':'End time',
    'event.common.chinese':'Chinese',
    'event.common.english':'English',
    'event.common.memberTeam':'Select a member or team to add to your event team',
    'event.common.save':'Save',
    'event.general.setting':'General Setting',
    'event.general.title':'Title',
    'event.general.subtitle':'SubTitle',
    'event.general.industry':'Industry',
    'event.general.sector':'Sector',
    'event.general.organization':'Select the role of your organization',
    'event.general.inContact':'Internal contact',
    'event.general.pubContact':'Public contact',
    'event.general.capacity':'Attendee capacity',
    'event.ge.capacity':'Please input the attendee capacity',
    'event.general.AArequired':'Attendee approval required',
    'event.general.eventType':'Event type',
    'event.general.disable':'Disable registration for this event',
    'event.general.setTime':'Set a specific start and date for registrations',
    'event.general.confirmationEmail':'Include e-ticket in confirmation email',
    'event.general.registrant':'One ticket per registrant',
    'event.template.SelectTemplate':'Select template',
    'event.template.defaultTemplate':'Default template',
    'event.template.cdefinition':'Content definition',
    'event.template.uploadBanner':'Upload banner image',
    'event.template.uploadlocation':'Upload location image',
    'event.template.upload':'Upload image',
    'event.template.summary':'Summary',
    'event.template.agenda':'Agenda',
    'event.template.speakers':'Speakers',
    'event.template.documents':'Documents',
    'event.template.sponsors':'Sponsors',
    'event.template.tickets':'Tickets',
    'event.template.payments':'',
    'event.template.changeFont':'Change Font',
    'event.template.changeColr':'Change main color',
    'event.template.ShowRegisterInfo':'Sign up and enquiry',
    'event.template.accountinformation':' Collection account information',
    'event.reg.tips':'Build your registration form with the below fields to gather attendee information',
    'event.reg.company':'Company:',
    'event.reg.position':'Position:',
    'event.reg.fname':'First Name:',
    'event.reg.lname':'Last Name:',
    'event.reg.phone':'Phone:',
    'event.reg.email':'Email:',
    'event.reg.companyAddress':'Company address:',
    'event.reg.PersonalAddress':'Address:',
    'event.reg.companyPhone':'Company phone:',
    'event.reg.companyIndustry':'Industry:',
    'event.reg.industry':'Sector:',
    'event.reg.country':'Country',
    'event.reg.state':'State / Province',
    'event.reg.city':'City',
    'event.reg.mandatory':'This is mandatory',
    'event.ticket.collectionAccount':'Collection Account Setting',
    'event.ticket.selectAccount':'Select a collection account',
    'event.ticket.bankname':'Official Bank Name',
    'event.ticket.name':'Name',
    'event.ticket.EditTitle':'Edit Ticket',
    'event.ticket.bankNumber':'Bank Account Number',
    'event.ticket.createTicket':'Creat Ticket',
    'event.ticket.discount':'Add discount',
    'event.ticket.Editdiscount':'Edit discount',
    'event.ticket.ticketName':'Ticket name',
    'event.ticket.priceType':'Price Type',
    'event.ticket.priceTypeStandard':'Standard price',
    'event.ticket.priceTypeFree':'Tickets for free',
    'event.ticket.ticketAva':'Available Tickets',
    'event.ticket.currency':'Currency',
    'event.ticket.price':'Price',
    'event.ticket.purchase':'Limit purchase quantity per registration',
    'event.ticket.limitNumber':'Number',
    'event.ticket.discountname':'Discount Name',
    'event.ticket.discountPer':'Depreciation',
    'event.ticket.limitDate':'Limit Duration',
    'event.ticket.noTicket':'No Event Tickets',
    'event.reg.CustomField':'CustomField',
    'event.manage.ModifyParticipant':'Edit Participant',
    
    'event.ticket.noTicketDes':'Once you have created your first Ticket, you will be able to add Event Discount.',
    'event.manage.ActivityOrganizer':'Activity Organizer',
    'event.manage.PendingApplication':'Pending Application',
    'event.manage.PayAmount':'Pay Amount',
    'event.manage.RecoverTicket':'Recover Ticket',
    'event.manage.Pending':'Pending',
    'event.manage.Refused':'Refused',
    'event.manage.NewParticipant':'New Participant',
    'event.manage.FirstName':'First Name',
    'event.manage.LastName':'Last Name',
    'event.manage.EMail':'E-mail',
    'event.manage.Telephone':'Telephone',
    'event.manage.CompanyName':'Company name',
    'event.manage.Position':'Position',
    'event.manage.RegistrationDate':'Registration date',
    'event.manage.TicketType':'Ticket type',
    'event.manage.discount':'Discount',
    'event.manage.PaymentInstrument':'Payment instrument',
    'event.manage.Actions':'Actions',
    'event.manage.CheckTheReg':'view registration information',
    'event.manage.Name':'Name',
    'event.manage.Industry':'Industry',
    'event.manage.approved':'Approved',
    'event.manage.Refuse':'Refuse',
    'event.manage.AllDiscount':'All Discount',
    'event.manage.passed':'Refused',
    'event.manage.checkIn':'Check In',
    'event.manage.Delete':'Delelte',
    'event.manage.BatchApproved':'Batch Approved',
    'event.manage.AllParticipator':'All participator',
    'event.manage.CancelledParticipator':'Cancelled participator',
    'event.manage.AllCategories':'All categories',
    'event.manage.Participator':'Participator',
    'event.manage.Speaker':'Speaker',
    'event.manage.Sponsor':'Sponsor',
    'event.manage.WithoutPrivileges':'Without privileges',
    'event.manage.Status':'Status',
    'event.manage.Paid':'Paid',
    'event.manage.Unpaid':'Unpaid',
    'event.manage.Registered':'Registered',
    'event.manage.NotSignIn':'Not sign in',
    'event.manage.PayStatus':'Pay status',
    'event.manage.ALLPayStatus':'All pay status',
    'event.manage.ALLCheckStatus':'All sign in state',
    'event.manage.SignInState':'Sign in state',
    'event.manage.ParticipatorType':'Participator type',
    'event.manage.Edit':'Edit',
    'event.manage.ConversionTicket':'Conversion ticket',
    'event.manage.ChangePayment':'Change payment status',
    'event.manage.changeDicountType':'Change discount type',
    'event.manage.CancelTheTicket':'Cancel the ticket',
    'event.manage.selectParticipator':'Select participator from CRM',
    'event.manage.Company':'Company',
    'event.manage.BatchCheckIn':'Batch check in',
    'event.manage.AllKinds':'All Kinds',
    'event.manage.Invalid':'Invalid',
    'event.manage.PaymentID':'Payment ID',
    'event.manage.Attendee':'Attendee',
    'event.manage.PaymentDate':'Payment Date',
    'event.manage.PaymentMethod':'Payment Method',
    'event.manage.Payer':'Payer',
    'event.manage.Payee':'Payee',
    // 'event.manage.PreferentialType':'Preferential type',
    'event.manage.Amount':'Amount',
    'event.manage.PayStatus':'Status',
    'event.manage.View':'View',
    'event.manage.RequireInvoice':'Require Invoice',
    'event.manage.InvalidatePayment':'Invalidate Payment',
    'event.manage.TotalAmount':'Total Amount',
    'event.manage.PaidAttendees':'Number of Paid Attendees',
    'event.manage.BulkPayment':'Bulk Payment',
    'event.manage.BatchInvoiceRequest':'Batch Invoice Request',
    'event.manage.BatchIssuedInvoice':'Batch Issued Invoice', 
    'event.manage.All':'All', 
    'event.manage.Checktheregistration':'view personal information',
    'event.manage.On-site':'On-site', 
    'event.manage.Express':'Express', 
    'event.manage.AllDeliveryMethods':'All Delivery Methods', 
    'event.manage.Issued':'Issued',
    'event.manage.Required':'Required',
    'event.manage.roleCategory':'Role Category',
    'event.manage.Issued':'Issued',
    'event.manage.Delivered':'Delivered',
    'event.manage.Received':'Received',
    'event.manage.AllInvoices':'All Invoices',
    'event.manage.VATSpecialInvoice':'VAT Special Invoice',
    'event.manage.VATInvoice':'VAT Invoice',
    'event.manage.ViewDetails':'View Details',
    'event.manage.ChangeStatus':'Change Status',
    'event.manage.CancelRequest':'Cancel Invoice Request',
    'event.manage.offlinePayment':'Offline Payment',
    'event.manage.onlinePayment':'Online Payment',
    'event.manage.transferAccounts':'Transfer Accounts',
    'event.manage.InvoiceStatus':'Invoice Status',
    'event.manage.OrderId':'OrderID',
    'event.manage.EventName':'EventName',
    'event.manage.Batchrecovery':'Batch Recovery',
    'event.message.RecoverySuccess':'Recovery Success',
    'event.manage.ApplicationDate':'ApplicationDate',
    'event.manage.InvioceType':'InvioceType',
    'event.manage.DeliveryMethods':'DeliveryMethods',
    'event.invoice.Modify':'Modify invoice information',
    
    'event.manage.DeliveryStatus':'Status',
    'event.manage.PaymentStatus':'Change payment status',
    
    'event.manage.Batchcheckin':'Batch check in',
    'event.manage.Batchchangediscount':'Batch change discount',
    'event.manage.Batchpayment':'Batch payment',
    'event.manage.Bulkinvoice':'Bulk invoice',
    'event.manage.Bulkcancellationtheticket':'Bulk cancellation the ticket',
    'event.manage.Mergerofmakeoutaninvoice':'Merger of make out an invoice',
     //async-validator createEvent
    'event.CE.messageTitle':'Please input event title！',
    'event.CE.messageLan':'Please select event language！',
    'event.CE.messageSD':'Please select start date！',
    'event.CE.messageED':'Please select end date！',
    'event.CE.messageST':'Please select start time！',
    'event.CE.messageET':'Please select end time！',
    'event.CE.messageSuccess':'The activity was successfully created, please complete the setting information!！',
     //general 
    'event.g.messageSubT':'Please input event subtitle!',
    'event.g.messageInd':'Please select industry!',
    'event.g.messageEC':'Please select external contact!',
    'event.layout.messagePublish':'Whether the release is confirmed, after the release will should not do more modification!',
    'event.layout.messagePublishSuccess':'Congratulations! The launch was a success!',
    'event.Confirm':'Confirm', 
    'event.Cancel':'Cancel',
    'event.SaveSuccess':'Saved successfully!',
    'event.g.timeFrom':'The start date cannot be later than the end date！',
    'event.g.timeTo':'The end date cannot be before the start date！',
    //ticket
    'event.ticket.messageTN':'Please input the ticket name!',
    'event.ticket.messagePT':'Please select the price type!',
    'event.ticket.messagePrice':'Please input the price!',
    'event.ticket.messagePrice':'Please input the price!',
    'event.ticket.messageDN':'Please input the discount name!',
    'event.ticket.messageDR':'Please enter discount rate !',
    'event.message.delete':'Delete success!',
    'event.messge.approveSuccessfully':'approved!',
    'event.message.RefusedSuccess':'Refuse to succeed！',
    'event.message.DNRePar':'Do not repeat participants!',
    'event.manage.BatchRefused':'Batch Refused',
    'event.message.cancelTicket':'The ticket cannot be restored after cancellation. Is it cancelled? ',
    'event.message.deleteSure':'The item cannot be restored after deletion，Are you sure want to delete this item? ',
    'event.message.lanTs':'Please note that your language settings are different than the primary language of this event!',
    'event.message.deletefailed':'Delete failed!',
    
    'event.home.event':'Event',
    'event.home.eventlist':'Events List',
    'event.home.company':'Company',
    'event.home.contact':'Contact',
    'event.home.addCompany':'Add Comapny',
    'event.home.addContact':'Add Contact',
    'event.home.Upcoming':'Upcoming',
    'event.home.InProgress':'In Progress',
    'event.home.past':'Past',
    'event.home.industryAnalysis':'Industry Analysis',
    'event.home.cityAnalysis':'City Analysis',
    'event.manage.cash':'Cash',
    'event.manage.recovery':'Recovery',
    'event.invoice.applicationNumber':'Application Number',
    'event.invoice.application':'Application',
    'event.invoice.InvoiceType':'Invoice Type',
    'event.invoice.SendType':'Delivery Methods',
    'event.invoice.InvoiceTitle':'Invoice Title',
    'event.invoice.taxid':'Tax ID Number',
    'event.invoice.Receivinginformation':'Receiving Information',
    'event.invoice.companyPhone':'Company Phone',
    'event.invoice.CompanyAddress':'Company Address',
    'event.invoice.InvoiceAmount':'Invoice Amount',
    'event.invoice.Improveinvoiceinformation':'Improve invoice information',
    'event.invoice.ConsigneeInformation':'Consignee Information',
    'event.message.application':'Please select the application!',
    'event.message.InvoiceType':'Please select the invoice type!',
    'event.message.SendType':'Please select the receiving information！',
    'event.message.InvoiceTitle':'Please input the invoice title!',
    'event.message.taxid':'Please input the tax id number！',
    'event.message.bankname':'Please input the bank name!',
    'event.message.banknumber':'Please input the bank number!',
    'event.message.qiyePhone':'Please input the company phone!',
    'event.message.qiyeAddress':'Please input the company address！',
    'event.message.ConsigneeInformation':'Please input the consignee information!',
    'event.message.companyPhone':'Please input the company phone!',
    'event.message.companyName':'Please input the company name!',
    'event.message.CompanyAddress':'Please input the company address！',
    'event.message.position':'Please input the position',
    'event.message.firstname':'Please input the first name',
    'event.message.lastname':'Please input the last name',
    'event.message.phone':'Please input the phone',
    'event.message.email':'Please input the E-mail',
    'event.message.Paymentinstrument':'Please select the payment instrument',
    'event.message.Discount':'Please select the discount',

    


    //lacey
    'event.content.Summary':'Summary',
    'event.content.Speakers':'Speakers',
    'event.content.Agenda':'Agenda',
    'event.content.Add venues':'Add venues',
    'event.content.Sponsors & Partners':'Sponsors & Partners',
    'event.content.Documents':'Documents',
    'event.content.Saved':'Saved',
    'event.content.Save':'Save',
    'event.content.Setup':'Setup',
    'event.content.Add speakers':'Add speakers',
    'event.content.this speakers has already exists':'this speakers has already exists',
    'event.content.Edit speakers':'Edit speakers',
    'event.content.Delete speakers':'Delete speakers',
    'event.content.Preview speakers':'Preview speakers',
    'event.content.Do you want to delete this speaker':'Do you want to delete this speakers?',
    'event.content.Add speaker successful':'Add speaker successful',
    'event.content.Search for the speaker':'Search for the speaker',
    'event.content.Add a new speaker':'Add a new speaker',
    'event.content.Speakers List':'Speakers List',
    'event.content.Upload avatar':'Upload avatar',
    'event.content.Contact Information':'Contact Information',
    'event.content.First name':'First name',
    'event.content.Last name':'Last name',
    'event.content.Position':'Position',
    'event.content.Company':'Company',
    'event.content.E-mail':'E-mail',
    'event.content.Order by':'Order by',
    'event.content.Website':'Website',
    "event.content.Description of your event's speaker":"Description of your event's speaker",
    'event.content.Cancel':'Cancel',
    'event.content.Day 1':'Day 1',
    'event.content.Track':'Track',
    'event.content.addPane':'Add Pane',
    'event.content.New Track':'New Track',
    'event.content.Edit Track':'Edit Track',
    'event.content.Delete Track':'Delete Track',
    'event.content.Session':'Session',
    'event.content.Create a new session':'Create a new session',
    'event.content.Edit a new session':'Edit a new session',
    'event.content.Delete a new session':'Delete a new session',
    'event.content.Do you want to delete this item':'Do you want to delete this item?',
    'event.content.Break':'Break',
    'event.content.Create a new break':'Create a new break',
    'event.content.Edit a new break':'Edit a new break',
    'event.content.Delete a new break':'Delete a new break',
    'event.content.Gap':'Gap',
    'event.content.Add a time gap':'Add a time gap',
    'event.content.Edit a time gap':'Edit a time gap',
    'event.content.Delete a time gap':'Delete a time gap',
    'event.content.Name':'Name',
    'event.content.Detailed address':'Detailed address',
    'event.content.Title':'Title',
    'event.content.Start time':'Start time',
    'event.content.End time':'End time',
    'event.content.Details':'Details',
    'event.content.Address':'Address',
    'event.content.Time':'Time',
    'event.content.GAP Time':'GAP Time',
    'event.content.Replenish meeting time by taking breaks':'Replenish meeting time by taking breaks',
    'event.content.Add a venue manually':'Add a venue manually',
    'event.content.Sort alphabetically':'Sort alphabetically',
    'event.content.Sort on usage':'Sort on usage',
    'event.content.Please input keywords':'Please input keywords',
    'event.content.Used/Saved venues':'Used/Saved venues',
    'event.content.Venue name':'Venue name',
    'event.content.Travel guidance':'Travel guidance',
    'event.content.Select this venue':'Select this venue',
    'event.content.Edit venue':'Edit venue',
    'event.content.Edit address':'Edit address',
    'event.content.Click here to upload a file':'Click here to upload a file',
    'event.content.Upload':'Upload',
    'event.content.Reset':'Reset',
    'event.content.Organizations':'Organizations',
    'event.content.Add organization':'Add organization',
    'event.content.Select organizations from deloitte entities':'Select organizations from deloitte entities',
    'event.content.Please enter the query entity':'Please enter the query entity',
    'event.content.Edit':'Edit',
    'event.content.Organization category':'sponsors',
    'event.content.Please input keywords':'Please input keywords',
    'event.content.Add Sponsors to organization':'Add Sponsors to organization',
    'event.content.Add sponsors':'Add sponsors',
    'event.content.Select sponsors from deloitte entities':'Select sponsors from deloitte entities',
    'event.content.Please enter the sponsor name':'Please enter the sponsor name',
    'event.content.Back to add sponsors':'Back to add sponsors',
    'event.content.Edit sponsors':'Edit sponsors',
    'event.content.Delete sponsors':'Delete sponsors',
    'event.content.Do you want to delete this sponsors':'Do you want to delete this sponsors？',
    'event.content.Do you want to delete this organization':'Do you want to delete this organization',
    'event.content.Create a new sponsor':'Create a new sponsor',
    'event.content.Add sponsor successful':'Add sponsor successful',
    'event.content.this sponsor has already exists':'This sponsor has already exists!',
    'event.content.Sponsors description':'Sponsors description',
    'event.content.Type of sponsorship amount':'Type of sponsorship amount',
    'event.content.Sponsorship amount':'Sponsorship amount',
    'event.content.Note':'Note',
    'event.content.Hide the sponsor on the event page':'Hide the sponsor on the event page',
    'event.content.Close':'Close',
    'event.content.You can only upload JPG file':'You can only upload JPG file',
    'event.content.You can only upload JPG file':'File must smaller than 1MB!',
    'event.content.Document list':'Document list',
    'event.content.Upload documents':'Upload document',
    'event.content.Delete documents':'Delete document',
    'event.content.file uploaded successfully':'File uploaded successfully',
    'event.content.file upload failed':'File upload failed',
    'event.content.No attached documents':'No attached documents',
    'event.content.Add documents':'Add documents',
    'event.content.Upload attached documents, which can be viewed or downloaded by participants':'Upload attached documents, which can be viewed or downloaded by participants',
    'event.content.Add campaign':'Add campaign',
    'event.content.Internal campaign name':'Internal campaign name',
    'event.content.Recipients':'Recipients',
    'event.content.Status':'Status',
    'event.content.Action':'Action',
    'event.content.Edit':'Edit',
    'event.content.Sent':'Sent',
    'event.content.Delete':'Delete',
    'event.content.Discount Type':'Discount Type',
    'event.content.Ticket type':'Ticket type',
    'event.content.Standard price':'Standard price',
    'event.content.Free price':'Free price',
    'event.content.Campaign':'Campaign',
    'event.content.Campaign Settings':'Campaign Settings',
    'event.content.Language':'Language',
    'event.content.Invitation list':'Invitation list',
    'event.content.View':'View',
    'event.content.Invitation list email':'Invitation list email',


    //jc
    'event.content.In Progress':'In Progress',
    'event.content.Upcoming':'Upcoming',
    'event.content.Past':'Past',
    'event.content.Register':'Register',
    'event.content.Agenda':'Agenda',
    'event.content.Speakers':'Speakers',
    'event.content.Tickets':'Tickets',
    'event.content.Payee (Entity)':'Payee (Entity)',
    'event.content.Documents':'Documents',
    'event.content.Registration and enquiry':'Registration and enquiry',
    'event.content.Date':'Date',
    'event.content.Address':'Address',
    'event.content.ReTips':'Please fill in the detailed information of participants (with * as required). If you have any questions, please contact us!',
    'event.content.Ticket information':'Ticket information',
    'event.content.Participant information':'Participant information',
    'event.content.Contact information':'Contact information',
    'event.content.Congratulations':'Congratulations on your registration!',
    'event.content.After approval':'After approval, you can pay online!',
    'event.content.My Registered Events':'My Registered Events',
    'event.content.My Upcoming Events':'My Upcoming Events',
    'event.content.My Past Events':'My Past Events',
    'event.content.Personal information Details':'Personal information Details',
    'event.content.Ticket information':'Ticket information',
    'event.content.Contact list':'Contact list',
    'event.content.Please input the original password':'Please input the original password',
    'event.content.Please input a new password':'Please input a new password',

    //  userIndex Start
    'event.content.Home':'Home',
    'event.content.My Event':'My Event',
    //  userIndex End

    //  globalHeader Start
    'event.content.Change user type':'Switch to administrator',
    'event.content.Personal information':'Personal information',
    'event.content.Personal Setting':'Personal Setting',
    'event.content.Log out':'Logout',
    'event.content.Log In':'LogIn',
    //  globalHeader End
    
    // personalSetting Start
    'event.content.Password setting': 'Password Setting',
    'event.content.Email address': 'Email address',
    'event.content.Please input the email address': 'Please input the email address!',
    'event.content.Original password': 'Original password',
    'event.content.New password': 'New password',
    'event.content.Confirm password': 'Confirm password',
    'event.content.Please input a confirm password': 'Please input a confirm password!',
    'event.content.Save password': 'Save',
    // personalSetting End

    // personalInfo Start
    'event.content.User picture': 'Photo',
    'event.content.User picture details': 'Please upload a clear photo, it would be only used in professional field.',
    'event.message.content.Company Address': 'Please select Company Address!',
    'event.content.Detail Company Address': 'Detail Company Address',
    'event.message.content.Detail Company Address': 'Please input Detail Company Address!',
    'event.message.reg.PersonalAddress': 'Please select Personal Address!',
    'event.message.content.Detail Personal Address': 'Please input Detail Personal Address!',
    'event.content.Detail Personal Address': 'Detail Personal Address',
    'event.content.Fapiao Name': 'Fapiao Name',
    'event.message.content.Fapiao Name': 'Please input Fapiao Name!',
    'event.content.Duty Paragraph': 'Duty Paragraph',
    'event.message.content.Duty Paragraph': 'Please input Duty Paragraph!',
    'event.content.Bank of Deposit': 'Bank of Deposit',
    'event.message.content.Bank of Deposit': 'Please input Bank of Deposit!',
    'event.content.Bank Account Number': 'Bank Account Number',
    'event.message.content.Bank Account Number': 'Please input Bank Account Number!',
    'event.content.Company Address': 'Company Address',
    'event.content.Company Contact Number': 'Company Contact Number',
    'event.content.Recepiant Name': 'Recepiant Name',
    'event.content.Recepiant Contact Number': 'Recepiant Contact Number',
    'event.content.Recepiant Address': 'Recepiant Address',
    'event.content.order': 'Order',
    'event.content.fullName': 'Name',
    'event.reg.action': 'Action',
    // personalInfo End

    // eventDetails Start
    'event.content.Basic Message': 'Basic Message',
    'event.content.Organizer': 'Organizer',
    'event.content.Contactor': 'Contactor',
    'event.content.Speaker': 'Speaker',
    'event.content.Geographical Position': 'Geographical Position',
    'event.content.CopyRight': 'Deloitte Event 2018 reserves the right of final interpretation',
    // eventDetails End
}