export default {
    'navbar.lang': '中文',
    'Home':'管理主页',
    'dashboard':'dashboard',
    'CRM':'客户关系',
    'Companies':'公司',
    'Contacts':'个人',
    'Events':'活动管理',
    'Draft':'编辑中的活动',
    'Upcoming':'即将开始的活动',
    'Current':'进行中的活动',
    'Past':'已结束的活动',
    'Finance':'财务收支',
    'Information':'财务信息',
    'Payment':'付款',
    'userInterface':'userInterface',
    'event.menu.SET UP':'设置',
    'event.menu.General Settings':'基本设置',
    'event.menu.Registration Form':'注册列表',
    'event.menu.Tickets & Coupons':'优惠及门票',
    'event.menu.Content Settings':'内容设置',
    'event.menu.Content Layout':'内容模板',
    'event.menu.Promote':'推广',
    'event.menu.Invitation':'邀请人列表',
    'event.menu.Manage':'管理',
    'event.menu.Registration List':'参与者',
    'event.menu.Paymetns':'付款',


    'event.content.Speakers':'演讲嘉宾',
    'event.content.Agenda':'日程安排',
    'event.content.Add venues':'添加场地',
    'event.content.Sponsors & Partners':'赞助商和合作伙伴',
    'event.content.Documents':'上传文档',
    'event.content.Saved':'保存',
    'event.content.Add speakers':'添加嘉宾',
    'event.content.Edit speakers':'编辑已添加嘉宾',
    'event.content.Delete speakers':'删除已添加嘉宾',
    'event.content.Preview speakers':'查看嘉宾详情',

    'event.content.Search for the speaker':'搜索嘉宾',
    'event.content.Add a new speaker':'手动添加新嘉宾',
    'event.content.Speakers List':'嘉宾列表',

    'event.content.Upload avatar':'照片上传',
    'event.content.First name':'姓',
    'event.content.Last name':'名',
    'event.content.Position':'职位',
    'event.content.Company':'公司',
    'event.content.E-mail':'邮件',
    'event.content.Order by':'顺序',
    'event.content.Website':'公司网站',
    "event.content.Description of your event's speaker":'描述嘉宾',
    'event.content.Cancel':'取消',
    'event.content.Day 1':'日期',
    'event.content.Track':'会场',
    'event.content.New Track':'新增会场地',
    'event.content.Edit Track':'修改会场地',
    'event.content.Delete Track':'删除会场地',
    'event.content.Session ':'议程',
    'event.content.Create a new session':'新增议程',
    'event.content.Edit a new session':'修改议程',
    'event.content.Delete a new session':'删除议程',
    'event.content.Break':'茶歇',
    'event.content.Create a new break':'新增茶歇',
    'event.content.Edit a new break':'修改茶歇',
    'event.content.Delete a new break':'删除茶歇',
    'event.content.Gap':'间隔',
    'event.content.Add a time gap':'新增间隔',
    'event.content.Edit a time gap':'修改间隔',
    'event.content.Delete a time gap':'删除间隔',
    'event.content.Name':'名称',
    'event.content.Detailed address':'详细地址',
    'event.content.Title':'标题',
    'event.content.Start time':'开始时间',
    'event.content.End time':'结束时间',
    'event.content.Details':'详细内容',
    'event.content.Address':'地点',
    'event.content.Time':'时间',
    'event.content.GAP Time':'间隔时间',
    'event.content.Replenish meeting time by taking breaks':'通过间隔时间来补充会议时间空隙',
    'event.content.Add a venue manually':'手动添加场地',
    'event.content.Sort alphabetically':'字母排序',
    'event.content.Sort on usage':'使用量排序',
    'event.content.Please input keywords':'搜索场地',
    'event.content.Used/Saved venues':'历史场地列表',
    'event.content.Venue name':'场地名称',
    'event.content.Edit address':'编辑位置',
    'event.content.Click here to upload a file':'点击上传附件',
    'event.content.Upload':'上传附件',
    'event.content.Reset':'重置',
    'event.content.Organizations':'活动组织',
    'event.content.Edit':'编辑活动组织',
    'event.content.Organization category':'组织目录',
    'event.content.Please input keywords':'搜索',
    'event.content.Add Sponsors to organization':'添加赞助商到活动组织',
    'event.content.Add sponsors':'新建赞助商',
    'event.content.Back to add sponsors':'返回添加',
    'event.content.Edit sponsors':'编辑赞助商',
    'event.content.Delete sponsors':'删除赞助商',
    'event.content.Add sponsors':'新建赞助商',
    'event.content.Sponsors description':'赞助商表述',
    'event.content.Type of sponsorship amount':'赞助金额类型',
    'event.content.Sponsorship amount':'赞助金额',
    'event.content.Note':'金额备注',
    'event.content.Hide the sponsor on the event page':'活动页面上隐藏此赞助',
    'event.content.Close':'关闭',
    'event.content.Document list':'文档列表',
    'event.content.Upload documents':'上传文档',
    'event.content.Delete documents':'删除文档',
    'event.content.No attached documents':'文档空空如也',
    'event.content.Add documents':'上传文档',
    'event.content.Upload attached documents, which can be viewed or downloaded by participants':'上传附件文档，可被参会者查看或下载',
}