export default {
    //tila
    'navbar.lang': '中文',
    'navbar.Welcome': '欢迎您！',
    'navbar.Please Login': '请登录！',
    'Home':'管理主页',
    'dashboard':'dashboard',
    'CRM':'客户关系管理',
    'Companies':'公司',
    'Contacts':'个人',
    'Events':'活动管理',
    'Draft':'编辑中的活动',
    'Upcoming':'即将开始的活动',
    'InProgress':'正在进行的活动',
    'Past':'已结束的活动',
    'Finance':'财务收支',
    'Invoice':'收款单位',
    'Payment':'付款',
    'userInterface':'用户界面',
    'Ticket':'票务',
    'Promotion':'优惠',
    'Exit':'退出活动管理',
    'event.menu.SET UP':'设置',
    'event.menu.General Settings':'基本设置',
    'event.menu.Registration Form':'注册列表',
    'event.menu.Tickets & Coupons':'票务设置',
    'event.menu.Content Settings':'内容设置',
    'event.menu.Content Layout':'内容模板',
    'event.menu.Promote':'推广',
    'event.menu.Invitation':'邀请人列表',
    'event.menu.EmailMarketing':'营销邮件',
    'event.menu.Manage':'管理',
    'event.menu.Registration List':'参与者',
    'event.menu.Paymetns':'付款',
    'event.menu.Invoice':'发票',
    'event.menu.summary':'活动摘要',
    'event.menu.speakers':'演讲嘉宾',
    'event.menu.agenda':'日程安排',
    'event.menu.venue':'添加场地',
    'event.menu.sponsors':'赞助商和合作伙伴',
    'event.menu.documents':'上传文档',
    'event.table.eventId':'活动编号',
    'event.table.eventTitle':'标题',
    'event.table.location':'地址',
    'event.table.startDate':'开始时间',
    'event.table.creation':'创建时间',
    'event.table.attendance':'参会人数',
    'event.table.checkedIn':'已签到',
    'event.table.action':'动作',
    'event.table.manage':'管理',
    'event.table.edit':'编辑',
    'event.table.preview':'预览',
    'event.table.duplicate':'复制',
    'event.table.delete':'删除',
    'event.createEvent':'新建活动',
    'event.create':'请填写所有活动详情',
    'event.common.eventTitle':'活动标题',
    'event.common.chinese':'中文',
    'event.common.english':'英文',
    'event.createEventDes':'创建活动',
    'event.common.Language':'语言设置',
    'event.common.startDate':'开始日期',
    'event.common.preview':'预览',
    'event.common.endDate':'结束日期',
    'event.common.publish':'发布',
    'event.common.startTime':'开始时间',
    'event.common.endTime':'结束时间',
    'event.common.memberTeam':'选择成员或小组',
    'event.common.save':'保存',
    'event.general.setting':'基本设置',
    'event.general.title':'活动标题',
    'event.general.subtitle':'副标题',
    'event.general.industry':'行业',
    'event.general.sector':'子行业',
    'event.general.organization':'活动组织角色',
    'event.general.inContact':'内部联系人',
    'event.general.pubContact':'外部联系人',
    'event.general.capacity':'设置参与者上限',
    'event.ge.capacity':'请设置参与者上限',
    'event.general.AArequired':'需审批参与者申请',
    'event.general.eventType':'活动类型',
    'event.general.setTime':'设置一个指定的注册开始和结束时间',
    'event.general.confirmationEmail':'确认邮件中包含电子门票',
    'event.general.registrant':'一个注册人仅限一张门票',
    'event.general.disable':'暂停注册',
    'event.template.SelectTemplate':'选择模板',
    'event.template.defaultTemplate':'默认模板',
    'event.template.cdefinition':'内容定义',
    'event.template.uploadBanner':'上传横幅图像',
    'event.template.uploadlocation':'上传地点图像',
    'event.template.upload':'上传图像',
    'event.template.summary':'活动详情',
    'event.template.agenda':'活动日程',
    'event.template.speakers':'演讲嘉宾',
    'event.template.documents':'共享文档',
    'event.template.sponsors':'合作伙伴',
    'event.template.tickets':'票务信息',
    'event.template.ShowRegisterInfo':'报名垂询',
    'event.template.payments':'',
    'event.template.changeFont':'模板字体',
    'event.template.changeColr':'主题颜色',
    'event.template.accountinformation':' 收款账户信息',
    'event.reg.tips':'请填写下列注册表格内容，完善参与者信息',
    'event.reg.company':'公司：',
    'event.reg.position':'职位：',
    'event.reg.fname':'姓：',
    'event.reg.lname':'名：',
    'event.reg.phone':'电话：',
    'event.reg.email':'邮箱：',
    'event.reg.companyAddress':'公司地址：',
    'event.reg.PersonalAddress':'个人地址：',
    'event.reg.companyPhone':'公司电话：',
    'event.reg.companyIndustry':'行业：',
    'event.reg.industry':'子行业',
    'event.reg.country':'国家',
    'event.reg.state':'州/省',
    'event.reg.city':'城市',
    'event.reg.mandatory':'必填项',
    'event.ticket.collectionAccount':'收款账户设置',
    'event.ticket.selectAccount':'选择收款账户',
    'event.ticket.bankname':'开户银行',
    'event.ticket.EditTitle':'编辑门票',
    'event.ticket.name':'银行名称',
    'event.ticket.bankNumber':'银行账号',
    'event.ticket.createTicket':'创建门票',
    'event.ticket.discount':'创建优惠',
    'event.ticket.Editdiscount':'编辑优惠',
    'event.ticket.ticketName':'门票名称',
    'event.ticket.priceType':'票价类型',
    'event.ticket.priceTypeStandard':'标准票价',
    'event.ticket.priceTypeFree':'免费票价',
    'event.ticket.ticketAva':'可用票量',
    'event.ticket.currency':'货币类型',
    'event.ticket.price':'票价',
    'event.ticket.purchase':'限定单个注册用户的购票数量',
    'event.ticket.limitNumber':'数量',
    'event.ticket.discountname':'优惠名称',
    'event.ticket.discountPer':'立减',
    'event.ticket.limitDate':'限制使用日期',
    'event.ticket.noTicket':'您还没有创建门票哟',
    'event.ticket.noTicketDes':'创建门票后才会有优惠信息，快动手试试吧',
    'event.manage.ActivityOrganizer':'活动组织成员',
    'event.manage.PendingApplication':'待审核申请',
    'event.manage.Pending':'待审核',
    'event.manage.Refused':'拒绝通过',
    'event.manage.passed':'审核未通过',
    'event.manage.NewParticipant':'新增参与者',
    'event.manage.ModifyParticipant':'编辑参与者',
    'event.manage.FirstName':'姓',
    'event.manage.LastName':'名',
    'event.manage.Telephone':'电话',
    'event.manage.EMail':'邮箱',
    'event.manage.CompanyName':'公司',
    'event.manage.Position':'职位',
    'event.manage.RegistrationDate':'注册日期',
    'event.manage.TicketType':'票务类型',
    'event.manage.discount':'优惠信息',
    'event.manage.PaymentInstrument':'支付方式',
    'event.manage.Actions':'动作',
    'event.manage.CheckTheReg':'查看注册信息',
    'event.manage.approved':'通过审核',
    // 'event.manage.Refuse':'拒绝通过',
    'event.manage.Delete':'删除',
    'event.manage.BatchApproved':'批量通过审核',
    'event.manage.AllParticipator':'参与者',
    'event.manage.CancelledParticipator':'取消的参与者',
    'event.manage.AllCategories':'所有分类',
    'event.manage.AllDiscount':'所有优惠',
    'event.manage.Participator':'参与者',
    'event.manage.Speaker':'嘉宾',
    'event.manage.Sponsor':'赞助商',
    'event.manage.WithoutPrivileges':'对应票务设置优惠',
    'event.manage.Status':'所有状态',
    'event.manage.Paid':'已支付',
    'event.manage.roleCategory':'角色类别',
    'event.manage.Unpaid':'未支付',
    'event.manage.Registered':'已签到',
    'event.manage.checkIn':'签到',
    'event.manage.NotSignIn':'未签到',
    'event.manage.PayStatus':'支付状态',
    'event.manage.SignInState':'签到状态',
    'event.manage.ParticipatorType':'参与者类型',
    'event.manage.Edit':'编辑',
    'event.manage.Name':'名称',
    'event.manage.Industry':'行业',
    'event.manage.Checktheregistration':'查看个人信息',
    'event.manage.ConversionTicket':'转换票务',
    'event.manage.ChangePayment':'更改支付状态',
    'event.manage.changeDicountType':'更改优惠类型',
    'event.manage.CancelTheTicket':'取消门票',
    'event.manage.selectParticipator':'从CRM中选择联系人',
    'event.manage.Company':'公司',
    'event.manage.BatchCheckIn':'批量签到',
    'event.manage.AllKinds':'所有分类',
    'event.manage.Invalid':'作废付款',
    'event.manage.PaymentID':'付款ID',
    'event.manage.Attendee':'参与者',
    'event.manage.PaymentDate':'付款日期',
    'event.manage.PaymentMethod':'付款方式',
    'event.manage.Payer':'付款人',
    'event.manage.Payee':'收款人',
    // 'event.manage.PreferentialType':'Preferential type',
    'event.manage.Amount':'金额',
    'event.manage.offlinePayment':'现金支付',
    'event.manage.onlinePayment':'扫码支付',
    'event.manage.transferAccounts':'转账支付',
    
    'event.manage.PayStatus':'付款状态',
    'event.manage.ALLPayStatus':'所有付款状态',
    'event.manage.ALLCheckStatus':'所有签到状态',
    'event.manage.View':'查看',
    'event.manage.RequireInvoice':'索要发票',
    'event.manage.InvalidatePayment':'作废付款',
    'event.manage.TotalAmount':'总金额',
    'event.manage.PaidAttendees':'已付款人数',
    'event.manage.BulkPayment':'批量付款',
    'event.manage.BatchInvoiceRequest':'批量索要发票',
    'event.manage.BatchIssuedInvoice':'批量开票', 
    'event.manage.All':'所有',
    'event.manage.On-site':'现场', 
    'event.manage.Express':'快递', 
    'event.manage.AllDeliveryMethods':'所有寄送类型', 
    'event.manage.Issued':'已开票',
    'event.manage.Required':'已请求',
    'event.manage.Delivered':'已寄送',
    'event.manage.Received':'已接收',
    'event.manage.AllInvoices':'全部发票',
    'event.manage.VATSpecialInvoice':'增值税专用票',
    'event.manage.VATInvoice':'增值税普通票',
    'event.manage.ViewDetails':'查看交易细节',
    'event.manage.ChangeStatus':'更改状态',
    'event.manage.CancelRequest':'取消发票申请',
    'event.manage.InvoiceStatus':'发票状态',
    'event.manage.PayAmount':'付款金额',
    'event.manage.RecoverTicket':'恢复门票',
    'event.reg.CustomField':'自定义字段',
    'event.invoice.Modify':'修改开票信息',
    
    'event.manage.OrderId':'订单ID',
    'event.manage.EventName':'活动名称',
    'event.manage.ApplicationDate':'申请日期',
    'event.manage.InvioceType':'发票类型',
    'event.manage.DeliveryMethods':'寄送方式',
    'event.manage.DeliveryStatus':'状态',
    'event.manage.PaymentStatus':'更改支付状态',
    'event.manage.Batchcheckin':'批量签到',
    'event.manage.Batchchangediscount':'批量更改优惠信息',
    'event.manage.Batchpayment':'批量付款',
    'event.manage.Bulkinvoice':'批量索要发票',
    'event.manage.Bulkcancellationtheticket':'批量取消门票',
    'event.manage.Mergerofmakeoutaninvoice':'合并开票',
    
    'event.CE.messageTitle':'请输入活动标题！',
    'event.CE.messageLan':'请选择语言设置！',
    'event.CE.messageSD':'请选择开始日期！',
    'event.CE.messageED':'请选择结束日期！',
    'event.CE.messageST':'请选择开始时间！',
    'event.CE.messageET':'请选择结束时间！',
    'event.CE.messageSuccess':'活动创建成功，请完善设置信息！',
    
     //general 
    'event.g.messageSubT':'请输入副标题!',
    'event.g.messageInd':'请选择行业信息！',
    'event.g.messageEC':'请选择外部联系人！',
    'event.layout.messagePublish':'是否确定发布，发布后将不宜做更多修改！',
    'event.layout.messagePublishSuccess':'恭喜你，发布成功！',
    'event.Confirm':'确认', 
    'event.Cancel':'取消',
    'event.manage.recovery':'恢复',
    'event.manage.Batchrecovery':'批量恢复',
    'event.message.RecoverySuccess':'恢复成功',
    'event.SaveSuccess':'保存成功!',
    'event.g.timeFrom':'开始时间不能在结束日期之后！',
    'event.g.timeTo':'结束日期不能在开始日期之前！',
     //ticket
    'event.ticket.messageTN':'请输入门票名称！!',
    'event.ticket.messagePT':'请选择票价类型!',
    'event.ticket.messagePrice':'请输入票价!',
    'event.ticket.messageDN':'请输入优惠名称！',
    'event.ticket.messageDR':'请输入优惠折扣比例!',
    'event.message.delete':'删除成功!',
    'event.messge.approveSuccessfully':'通过审核！',
    'event.message.RefusedSuccess':'拒绝通过成功',
    'event.message.DNRePar':'请勿重复添加参与者！',
    'event.manage.BatchRefused':'批量拒绝通过',
    'event.message.cancelTicket':'取消门票后无法恢复，是否确认取消？ ',
    'event.message.deleteSure':'删除后将无法恢复，是否确认删除? ',
    'event.message.lanTs':'请注意，您目前的语言模式与初始活动语言设置不同!',
    'event.message.deletefailed':'删除失败!',
    'event.home.event':'活动',
    'event.home.eventlist':'活动列表',
    'event.home.company':'公司',
    'event.home.contact':'个人',
    'event.home.addCompany':'新增公司',
    'event.home.addContact':'新增联系人',
    'event.home.Upcoming':'即将开始',
    'event.home.InProgress':'正在进行',
    'event.home.past':'已结束',
    'event.home.industryAnalysis':'行业分析',
    'event.home.cityAnalysis':'城市分析',
    'event.manage.cash':'现金',
    'event.invoice.applicationNumber':'申请人数',
    'event.invoice.application':'申请人',
    'event.invoice.InvoiceType':'发票类型',
    'event.invoice.SendType':'寄送方式',
    'event.invoice.InvoiceTitle':'发票抬头',
    'event.invoice.taxid':'纳税人识别号',
    'event.invoice.Receivinginformation':'寄送方式',
    'event.invoice.companyPhone':'企业电话',
    'event.invoice.CompanyAddress':'企业地址',
    'event.invoice.InvoiceAmount':'发票金额',
    'event.invoice.Improveinvoiceinformation':'完善发票信息',
    'event.invoice.ConsigneeInformation':'收件信息',
    'event.message.application':'请选择申请人!',
    'event.message.InvoiceType':'请选择发票类型!',
    'event.message.SendType':'请选择寄送方式！',
    'event.message.InvoiceTitle':'请填写发票抬头!',
    'event.message.taxid':'请填写纳税人识别号！',
    'event.message.bankname':'请填写开户银行!',
    'event.message.banknumber':'请填写银行账号!',
    'event.message.qiyePhone':'请填写企业电话!',
    'event.message.qiyeAddress':'请填写企业地址！',
    'event.message.ConsigneeInformation':'请填写收件信息!',
    'event.message.companyPhone':'请填写公司电话!',
    'event.message.CompanyAddress':'请填写公司地址！',
    'event.message.companyName':'请填写公司名称!',
    'event.message.position':'请填写职位',
    'event.message.firstname':'请填写姓氏',
    'event.message.lastname':'请填写名字',
    'event.message.phone':'请填写电话号码',
    'event.message.email':'请填写邮箱地址',
    'event.message.Paymentinstrument':'请选择支付方式',
    'event.message.Discount':'请选择优惠方式',


    //lacey

    'event.content.Summary':'活动摘要',
    'event.content.Speakers':'演讲嘉宾',
    'event.content.Agenda':'日程安排',
    'event.content.Add venues':'添加场地',
    'event.content.Sponsors & Partners':'赞助商和合作伙伴',
    'event.content.Documents':'上传文档',
    'event.content.Saved':'保存',
    'event.content.Save':'保存',
    'event.content.Setup':'设置',
    'event.content.Add speakers':'添加嘉宾',
    'event.content.this speakers has already exists':'该嘉宾已存在',
    'event.content.Edit speakers':'编辑已添加嘉宾',
    'event.content.Delete speakers':'删除已添加嘉宾',
    'event.content.Preview speakers':'查看嘉宾详情',
    'event.content.Do you want to delete this speaker':'是否要删除该嘉宾？',
    'event.content.Add speaker successful':'添加嘉宾成功',
    'event.content.Search for the speaker':'搜索嘉宾',
    'event.content.Add a new speaker':'手动添加新嘉宾',
    'event.content.Speakers List':'嘉宾列表',
    'event.content.Contact Information':'联系人信息',
    'event.content.Upload avatar':'照片上传',
    'event.content.First name':'姓',
    'event.content.Last name':'名',
    'event.content.Position':'职位',
    'event.content.Company':'公司',
    'event.content.E-mail':'邮件',
    'event.content.Order by':'顺序',
    'event.content.Website':'公司网站',
    "event.content.Description of your event's speaker":'描述嘉宾',
    'event.content.Cancel':'取消',
    'event.content.Day 1':'日期',
    'event.content.Track':'会场',
    'event.content.addPane':'添加活动时间',
    'event.content.New Track':'新增会场地',
    'event.content.Edit Track':'修改会场地',
    'event.content.Delete Track':'删除会场地',
    'event.content.Session':'议程',
    //'event.content.Create a new session':'新增议程',
    'event.content.Edit a new session':'修改议程',
    'event.content.Delete a new session':'删除议程',
    'event.content.Do you want to delete this item':'是否要删除？',
    'event.content.Break':'茶歇',
    'event.content.Create a new break':'新增茶歇',
    'event.content.Edit a new break':'修改茶歇',
    'event.content.Delete a new break':'删除茶歇',
    'event.content.Gap':'间隔',
    'event.content.Add a time gap':'新增间隔',
    'event.content.Edit a time gap':'修改间隔',
    'event.content.Delete a time gap':'删除间隔',
    'event.content.Name':'名称',
    'event.content.Detailed address':'详细地址',
    'event.content.Title':'标题',
    'event.content.Start time':'开始时间',
    'event.content.End time':'结束时间',
    'event.content.Details':'详细内容',
    'event.content.Address':'地点',
    'event.content.Time':'时间',
    'event.content.GAP Time':'间隔时间',
    'event.content.Replenish meeting time by taking breaks':'通过间隔时间来补充会议时间空隙',
    'event.content.Add a venue manually':'手动添加场地',
    'event.content.Sort alphabetically':'字母排序',
    'event.content.Sort on usage':'使用量排序',
    'event.content.Please input keywords':'搜索场地',
    'event.content.Used/Saved venues':'历史场地列表',
    'event.content.Venue name':'场地名称',
    'event.content.Travel guidance':'行程指南',
    'event.content.Edit venue':'修改场地',
    'event.content.Edit address':'编辑位置',
    'event.content.Select this venue':'选择此场地',
    'event.content.Click here to upload a file':'点击上传附件',
    'event.content.Upload':'上传附件',
    'event.content.Reset':'重置',
    'event.content.Organizations':'活动组织',
    'event.content.Add organization':'添加组织',
    'event.content.Select organizations from deloitte entities':'从德勤实体中选择组织',
    'event.content.Please enter the query entity':'请输入查询实体',
    'event.content.Edit':'编辑活动组织',
    'event.content.Organization category':'活动赞助',
    'event.content.Please input keywords':'搜索',
    'event.content.Add Sponsors to organization':'添加赞助商到活动组织',
    'event.content.Add sponsors':'新建赞助商',
    'event.content.Select sponsors from deloitte entities':'从德勤实体中选择赞助商',
    'event.content.Please enter the sponsor name':'请输入赞助商名称',
    'event.content.Back to add sponsors':'返回添加',
    'event.content.Edit sponsors':'编辑赞助商',
    'event.content.Delete sponsors':'删除赞助商',
    'event.content.Do you want to delete this sponsors':'是否要删除该赞助商？',
    'event.content.Do you want to delete this organization':'是否要删除该活动组织？',
    'event.content.Create a new sponsor':'添加赞助商',
    'event.content.Add sponsor successful':'添加赞助商成功',
    'event.content.this sponsor has already exists':'该赞助商已存在',
    'event.content.Sponsors description':'赞助商表述',
    'event.content.Type of sponsorship amount':'赞助金额类型',
    'event.content.Sponsorship amount':'赞助金额',
    'event.content.Note':'金额备注',
    'event.content.Hide the sponsor on the event page':'活动页面上隐藏此赞助',
    'event.content.Close':'关闭',
    'event.content.You can only upload JPG file':'请上传jpg类型的文件',
    'event.content.Image must smaller than 1MB':'文件大小不超过1MB',
    'event.content.Document list':'文档列表',
    'event.content.Upload documents':'上传文档',
    'event.content.Delete documents':'删除文档',
    'event.content.No attached documents':'文档空空如也',
    'event.content.file uploaded successfully':'上传成功',
    'event.content.file upload failed':'上传失败',
    'event.content.Add documents':'上传文档',
    'event.content.Upload attached documents, which can be viewed or downloaded by participants':'上传附件文档，可被参会者查看或下载',
    'event.content.Add campaign':'新增营销邮件',
    'event.content.Internal campaign name':'邮件标题',
    'event.content.Recipients':'收件人',
    'event.content.Status':'状态',
    'event.content.Action':'动作',
    'event.content.Edit':'修改',
    'event.content.Sent':'发送',
    'event.content.Delete':'删除',
    'event.content.Discount Type':'优惠类型',
    'event.content.Ticket type':'票务类型',
    'event.content.Standard price':'标准票价',
    'event.content.Free price':'免费票价',
    'event.content.Campaign':'营销名称',
    'event.content.Campaign Settings':'营销邮件设置',
    'event.content.Language':'语言',
    'event.content.Invitation list':'邀请人',
    'event.content.View':'查看',
    'event.content.Invitation list email':'邀请人邮箱',

    //jc
    'event.content.In Progress':'正在进行',
    'event.content.Upcoming':'即将开始',
    'event.content.Past':'已结束',
    'event.content.Register':'注册',
    'event.content.Agenda':'日程安排',
    'event.content.Speakers':'演讲嘉宾',
    'event.content.Tickets':'票务信息',
    'event.content.Payee (Entity)':'收款账户信息',
    'event.content.Documents':'文档信息',
    'event.content.Registration and enquiry':'报名与垂询',
    'event.content.Date':'日期',
    'event.content.Address':'地址',
    'event.content.ReTips':'请填上参与者的具体信息(带*为必填项)，如有任何问题请联系我们',
    'event.content.Ticket information':'门票信息',
    'event.content.Participant information':'参与者信息',
    'event.content.Contact information':'选择联系方式',
    'event.content.Congratulations':'恭喜你成功注册!',
    'event.content.After approval':'通过审核后，即可选择网上付款！',
    'event.content.My Registered Events':'我注册的活动',
    'event.content.My Upcoming Events':'我即将开始的活动',
    'event.content.My Past Events':'我参与过的活动',
    'event.content.Personal information Details':'详细信息',
    'event.content.Ticket information':'票务信息',
    'event.content.Contact list':'联系人名单',
    'event.content.Please input the original password':'请输入原始密码',
    'event.content.Please input a new password':'请输入新密码',
    //  globalHeader Start
    'event.content.Change user type': '切换用户角色',
    'event.content.Personal information': '个人中心',
    'event.content.Personal Setting': '个人设置',
    'event.content.Log out': '退出登录',
    'event.content.Log In': '登录',
    //  globalHeader End

    // userIndex Start
    'event.content.Home': '首页',
    'event.content.My Event': '我的活动',
    // userIndex End

    // personalSetting Start
    'event.content.Password setting': '密码设置',
    'event.content.Email address': '邮箱地址',
    'event.content.Please input the email address': '请输入邮箱地址！',
    'event.content.Original password': '旧密码',
    'event.content.New password': '新密码',
    'event.content.Confirm password': '确认密码',
    'event.content.Please input a confirm password': '请输入确认密码！',
    'event.content.Save password': '保存密码',
    // personalSetting End

    // personalInfo Start
    'event.content.User picture': '照片',
    'event.content.User picture details': '请上传一张清晰显示正脸的照片，这将用于专业范围！',
    'event.message.content.Company Address': '请选择公司地址',
    'event.content.Detail Company Address': '公司详细地址',
    'event.message.content.Detail Company Address': '请输入公司详细地址！',
    'event.message.reg.PersonalAddress': '请选择个人地址！',
    'event.message.content.Detail Personal Address': '请输入个人详细地址',
    'event.content.Detail Personal Address': '个人详细地址',
    'event.content.Fapiao Name': '发票抬头',
    'event.message.content.Fapiao Name': '请输入发票抬头！',
    'event.content.Duty Paragraph': '税号',
    'event.message.content.Duty Paragraph': '请输入税号！',
    'event.content.Bank of Deposit': '开户银行',
    'event.message.content.Bank of Deposit': '请输入开户银行！',
    'event.content.Bank Account Number': '银行账号',
    'event.message.content.Bank Account Number': '请输入银行账号！',
    'event.content.Company Address': '企业地址',
    'event.content.Company Contact Number': '企业电话',
    'event.content.Recepiant Name': '收件联系人',
    'event.content.Recepiant Contact Number': '收件联系人电话',
    'event.content.Recepiant Address': '收件地址',
    'event.content.order': '序号',
    'event.content.fullName': '姓名',
    'event.reg.action': '操作',
    // personalInfo End

    // eventDetails Start
    'event.content.Basic Message': '基本信息',
    'event.content.Organizer': '主办方',
    'event.content.Contactor': '联系人',
    'event.content.Speaker': '演讲嘉宾',
    'event.content.Geographical Position': '地理位置',
    'event.content.CopyRight': '@Deloitte Event 2018 最终解释权',
    // eventDetails End
}